//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab23.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public System.Guid SessionID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public System.DateTime LoginTime { get; set; }
        public Nullable<System.DateTime> LogoffTime { get; set; }

        public Session()
        {
            SessionID = Guid.NewGuid();
            UserID = null;
            LoginTime = DateTime.Now;
            LogoffTime = DateTime.Now.AddMinutes(30);
        }

        public Session(Guid UID)
        {
            SessionID = Guid.NewGuid();
            UserID = UID;
            LoginTime = DateTime.Now;
            LogoffTime = DateTime.Now.AddMinutes(30);
        }

        public void LoginAs(Guid UID)
        {
            UserID = UID;
            this.UpdateExpiry();
        }

        public void UpdateExpiry()
        {
            LogoffTime = DateTime.Now.AddMinutes(30);
        }

        public override string ToString()
        {
            return SessionID.ToString("D");
        }

        public virtual User User { get; set; }
    }
}
